name: BlockEraTwoFA
main: space.blockera.twofa.BlockEraTwoFAPlugin
version: "${version}"
description: "TOTP 2FA для Paper 1.21.x"
api-version: "1.21"
authors: ["BlockEra"]
commands:
  2fa:
    description: "Управление двухфакторной аутентификацией"
    usage: "/2fa <setup|confirm|status|disable|reload> [код]"
    permission: blockera.twofa.use
permissions:
  blockera.twofa.use:
    default: true
  blockera.twofa.admin:
    default: op
  blockera.twofa.bypass:
    default: false
  blockera.twofa.required:
    description: "Если у игрока есть эта пермишен — 2FA обязательно"
    default: false
